name: Airway Innovations
favicon: null
layout_spectrum: 0.5145317381247878
typography_spectrum: 0.05352665903046727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9732551849447191
  lightness: 0.7364247862715274
  saturation: 0.9145371676422656
  rhythmicContrast: 0.2780629701446742
purpose: []
