analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9145372
  brandStrength: 0.9732551849447191
  lightness: 0.718638
  brandColors:
    - '#060606'
    - '#1F1F1F'
    - '#484848'
    - '#A6A6A8'
    - '#6F6D6F'
  rhythmicContrast: 0.278063
typography_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.6344086
favicon: null
name: Airway Innovations
